L0:     PUSH         1         ; Declaring INT i1
        PUSH         1         ; Declaring INT i2
        PUSH         1         ; Declaring BOOL b1
        PUSH         1         ; Declaring CHAR c1
        LOADL        16
        LOADL        2
        LOADL        8
        CALL         neg       ; Integer negation
        CALL         mult      ; Multiplication
        CALL         add       ; Adition
        STORE(1)     1[SB]     ; Assigning i2
        LOAD(1)      1[SB]     ; Loading i2 for next expression
        STORE(1)     0[SB]     ; Assigning i1
        LOADL        12
        LOADL        5
        CALL         div       ; Devide
        LOADL        5
        CALL         mult      ; Multiplication
        LOADL        12
        LOADL        5
        CALL         mod       ; Modulo
        CALL         add       ; Adition
        LOADL        12
        LOADL        1
        CALL         eq
        LOADL        6
        LOADL        6
        CALL         ge        ; Greater than or equal
        CALL         and
        STORE(1)     2[SB]     ; Assigning b1
        LOADL        122       ; Loading character 'z'
        STORE(1)     3[SB]     ; Assigning c1
        LOAD(1)      0[SB]     ; Loading i1
        CALL         putint    ; Print int
        CALL         puteol
        LOAD(1)      1[SB]     ; Loading i2
        CALL         putint    ; Print int
        CALL         puteol
        LOAD(1)      2[SB]     ; Loading b1
        LOADL        1
        LOADL        1
        CALL         eq
        JUMPIF(0)    L1[CB]    ; Printing True or jump
        LOADL        116       ; Loading character
        CALL         put       ; Print character
        LOADL        114       ; Loading character
        CALL         put       ; Print character
        LOADL        117       ; Loading character
        CALL         put       ; Print character
        LOADL        101       ; Loading character
        CALL         put       ; Print character
        JUMP         L2[CB]    ; Printing False
L1:     LOADL        102       ; Loading character
        CALL         put       ; Print character
        LOADL        97        ; Loading character
        CALL         put       ; Print character
        LOADL        108       ; Loading character
        CALL         put       ; Print character
        LOADL        115       ; Loading character
        CALL         put       ; Print character
        LOADL        101       ; Loading character
        CALL         put       ; Print character
L2:     CALL         puteol
        LOAD(1)      3[SB]     ; Loading c1
        CALL         put       ; Print character
        CALL         puteol
        POP(0)       4
        HALT                   ; Generated by the Noot Compiler (2013/07/08 23:01)
