L0:     PUSH         1         ; Declaring INT i1
        PUSH         1         ; Declaring INT i2
        PUSH         1         ; Declaring INT i3
        LOADL        1
        STORE(1)     0[SB]     ; Assigning i1
        LOADL        2
        STORE(1)     1[SB]     ; Assigning i2
        LOADL        3
        STORE(1)     2[SB]     ; Assigning i3
        PUSH         1         ; Declaring INT i1
        LOADL        3
        STORE(1)     3[SB]     ; Assigning constant i1
        PUSH         1         ; Declaring INT i2
        LOADL        5
        STORE(1)     4[SB]     ; Assigning i2
        PUSH         1         ; Declaring INT i3
        LOADL        2
        STORE(1)     5[SB]     ; Assigning constant i3
        LOAD(1)      3[SB]     ; Loading i1
        LOAD(1)      5[SB]     ; Loading i3
        CALL         add       ; Adition
        LOAD(1)      4[SB]     ; Loading i2
        LOADL        1
        CALL         eq
        LOADL        1
        LOADL        1
        CALL         eq
        JUMPIF(0)    L1[CB]    ; Printing True or jump
        LOADL        116       ; Loading character
        CALL         put       ; Print character
        LOADL        114       ; Loading character
        CALL         put       ; Print character
        LOADL        117       ; Loading character
        CALL         put       ; Print character
        LOADL        101       ; Loading character
        CALL         put       ; Print character
        JUMP         L2[CB]    ; Printing False
L1:     LOADL        102       ; Loading character
        CALL         put       ; Print character
        LOADL        97        ; Loading character
        CALL         put       ; Print character
        LOADL        108       ; Loading character
        CALL         put       ; Print character
        LOADL        115       ; Loading character
        CALL         put       ; Print character
        LOADL        101       ; Loading character
        CALL         put       ; Print character
L2:     CALL         puteol
        LOAD(1)      1[SB]     ; Loading i2
        CALL         putint    ; Print int
        CALL         puteol
        POP(0)       6
        HALT                   ; Generated by the Noot Compiler (2013/07/09 11:43)
