L0:     PUSH         1         ; Declaring INT i1
        LOADL        1
        STORE(1)     0[SB]     ; Assigning constant i1
        POP(0)       1
        HALT                   ; Generated by the Noot Compiler (2013/07/09 11:43)
