L0:     PUSH         1         ; Declaring INT i1
        LOADL        3
        LOADL        0
        CALL         div       ; Devide
        STORE(1)     0[SB]     ; Assigning i1
        POP(0)       1
        HALT                   ; Generated by the Noot Compiler (2013/07/09 13:20)
