L0:     PUSH         1         ; Declaring BOOL g
        PUSH         1         ; Declaring INT h
        PUSH         1         ; Declaring INT i
        LOADL        5
        STORE(1)     2[SB]     ; Assigning i
        LOADA(1)     1[SB]     ; Loading address of h
        CALL         getint    ; Reading int h
        LOAD(1)      0[SB]     ; Loading g
        LOADL        1         ; True Boolean
        LOADL        1
        CALL         eq
        JUMPIF(0)    L3[CB]    ; If (jump to else)
        PUSH         1         ; Declaring INT j
        LOADL        1         ; True Boolean
        JUMPIF(0)    L1[CB]    ; If (jump to else)
        PUSH         1         ; Declaring INT i
        LOADL        5
        STORE(1)     4[SB]     ; Assigning i
        LOAD(1)      4[SB]     ; Loading i for next expression
        JUMP         L2[CB]    ; Else (jump over else)
L1:     LOADL        6
L2:     STORE(1)     3[SB]     ; Assigning j
        JUMP         L3[CB]    ; Else (jump over else)
L3:     POP(0)       0
        HALT                   ; Generated by the Noot Compiler (2013/07/07 13:22)
